"""Copy the shared header + .btn rules from style.css into explorer.css (keeps both pages identical)."""
import pathlib,re
R=pathlib.Path(__file__).resolve().parent.parent
t=(R/'assets/css/style.css').read_text()
ex=R/'assets/css/explorer.css';x=ex.read_text();x=x[:x.index('\n/* ===== shared header')]
css=re.sub(r'/\*.*?\*/','',t,flags=re.S)
def split(s):
    out=[];d=0;st=0
    for k,ch in enumerate(s):
        if ch=='{':d+=1
        elif ch=='}':
            d-=1
            if d==0: out.append(s[st:k+1].strip()); st=k+1
    return out
pre=re.compile(r'^(\.flag|\.btn|\.hdr|\.brand|\.nav-open)')
out=[]
for r in split(css):
    sel=r[:r.index('{')]
    if r.startswith('@keyframes arcycle'): out.append(r)
    elif r.startswith('@media'):
        sub=[y for y in split(r[r.index('{')+1:-1]) if pre.match(y)]
        if sub: out.append(sel+'{'+''.join(sub)+'}')
    elif any(pre.match(y.strip()) for y in sel.split(',')): out.append(r)
add='\n/* ===== shared header (generated by tools/sync_header.py — do not edit) ===== */\n:root{--de1:#1a1a1a;--de2:#dd0000;--de3:#ffce00;--orange-hi:#ff9459}\nimg{max-width:100%}\n'+'\n'.join(out)+'\n.hdr{position:sticky;top:0}.hdr.hide{transform:none}.hdr__in{width:min(100% - 2*var(--gut),1320px);margin-inline:auto}.hdr nav{margin-left:auto;margin-right:1.4rem}@media (max-width:1020px){.hdr nav{display:flex;position:static;opacity:1;visibility:visible;transform:none;background:none;border:0;box-shadow:none;padding:0}.hdr nav a{padding:0;border:0;font-size:.85rem}}@media (max-width:560px){.hdr nav{display:none}.hdr__cta{display:inline-flex}}\n'
ex.write_text(x+add);print(len(out))
